name: chandoiqua
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'







dependencies:
  flutter:
    sdk: flutter


  
  
  icons_plus: ^4.0.0
  cupertino_icons: ^1.0.6
  firebase_core: ^2.27.1
  google_sign_in: ^6.2.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  http: ^1.2.1

  shared_preferences: ^2.2.2
  bloc: ^8.1.3
  intl: ^0.18.1
  flutter_bloc: ^8.1.4
  firebase_ui_auth: ^1.13.1
  firebase_ui_oauth_google: ^1.3.1
  googleapis_auth: ^1.5.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.8
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10





flutter:

  
  
  
  uses-material-design: true
  assets:
    - assets/images/bg1.png
    - assets/images/backgroud.png
    - assets/logos/google_logo.png
    - assets/images/google_logo.png
    - assets/images/bgtour.jpeg
    - assets/images/IMG_7985.png
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
